Added Juno RPC Schema
NethermindEth/juno pull request #1055
Opened 2023-08-09 16:21 UTC by Brivan-26

Closes [Schema for custom RPC endpoints](https://github.com/NethermindEth/juno/issues/936)

2023-08-09 19:05 UTC, Brivan-26 commented on juno_rpc_api.json
> +            "FELT": {
You mean the common schemas such as `FELT` and `TXN_HASH` should be referred directly to the Starknet RPC spec ?

2023-08-09 19:11 UTC, joshklop commented on juno_rpc_api.json
> +            "FELT": {
Preferably, yes.

2023-08-09 19:21 UTC, Brivan-26 commented on juno_rpc_api.json
> +            "FELT": {
They don't refer to the Starknet RPC space. I see it better to not, so who ever is using the spec doesn't need to switch between multiple standards, but find all components in the same place. What do you think?

2023-08-09 19:22 UTC, joshklop commented on juno_rpc_api.json
> +            "FELT": {
If Pathfinder doesn't then let's not worry about it.

2023-08-15 01:35 UTC, joshklop requested changes

2023-08-15 01:35 UTC, joshklop commented on juno_rpc_api.json
> +            "description": "This method returns the current status of a transaction. The status is comprised of both finality and execution statuses",
Can we remove the description or summary? Seems redundant to have both.

2023-08-15 14:21 UTC, joshklop commented on juno_rpc_api.json
> +                    "1",
The strings should be `"ACCEPTED_ON_L1"`, etc.

2023-08-15 21:01 UTC, joshklop approved these changes

2023-08-15 21:46 UTC, merged