git action for juno dev
NethermindEth/juno pull request #1149
Opened 2023-08-23 13:19 UTC by ToluwalopeAyo

2023-08-24 06:33 UTC, Manjeet-Nethermind approved these changes

2023-08-24 06:33 UTC, Manjeet-Nethermind commented
LGTM

2023-08-28 10:40 UTC, Manjeet-Nethermind approved these changes
LGTM

2023-09-04 13:19 UTC, joshklop commented
@ToluwalopeAyo Mind rebasing? Happy to merge this if it's ready.

2023-09-11 08:37 UTC, wojciechos commented on .github/workflows/docker-image-build-push.yml
> +      production_deployment:
Should it be here? Its not used anywhere.

2023-09-11 08:37 UTC, wojciechos commented on .github/workflows/docker-image-build-push.yml
> +  dev_repository_dispatch:
This workflow was originally meant just to `Build and publish Docker image`. If we're thinking of deploying, perhaps we should create a separate workflow for that, maybe using the `workflow_call` feature to reuse building docker logic. This approach might help us keep things clearer and more organized.

2023-09-11 08:37 UTC, wojciechos commented on .github/workflows/docker-image-build-push.yml
> +          TESTNET: apps/juno-dev/overlays/dev-integration/config.yaml
Can we use `INTEGRATION` instead of `TESTNET`?

2023-09-11 08:37 UTC, wojciechos commented on .github/workflows/publish-dispatch-prod.yml
> +
unnecessary empty line

2023-09-11 08:37 UTC, wojciechos commented on .github/workflows/publish-dispatch-prod.yml
> +      - name: Repository Dispatch
What are we triggering here? Is this related to a k8 deployment? `Repository Dispatch` doesn't provide much context. Can we consider a more descriptive name?

2023-09-12 07:37 UTC, wojciechos commented on .github/workflows/build-and-deploy.yml
> +    branches: [master]
Should be `[main]`, not `[master]`.

2023-09-12 07:37 UTC, wojciechos commented on .github/workflows/publish-dispatch-prod.yml
> +name: Dispatch Render for Juno Prod
I guess we don't need this file anymore.

2023-09-12 07:45 UTC, wojciechos commented on .github/workflows/build-and-deploy.yml
> +    needs: [docker_build_and_publish, deploy_to_staging]
Do we need `docker_build_and_publish` here? I guess `deploy_to_staging` already implicate that `docker_build_and_publish` has been run.

2023-09-12 07:54 UTC, wojciechos commented on .github/workflows/build-and-deploy.yml
> +          tags: nethermindeth/juno:${{ github.event.inputs.tag }}
There is no `github.event.inputs.tag` defined, it won't work. Shouldn't be `IMAGE_TAG ` here?

2023-09-12 07:58 UTC, wojciechos commented on .github/workflows/build-and-deploy.yml
> +      IMAGE_TAGE: ${{ steps.image_tag.outputs.IMAGE_TAG }}
typo  IMAGE_TAG**E**

2023-09-12 08:03 UTC, wojciechos commented on .github/workflows/build-and-deploy.yml
> +          TESTNET: apps/juno-staging/overlays/staging-integration/config.yaml
Can we name INTEGRATION network as INTEGRATION, not as TESTNET? I mean Goerli is also a testnet so it can be misleading.

2023-09-12 08:31 UTC, ToluwalopeAyo commented on .github/workflows/build-and-deploy.yml
> +            -d '{"event_type": "${{ env.EVENT_NAME }}", "client_payload":{"name": "${{ env.EVENT_NAME }}", "goerli_config": "${{ env.GOERLI }}", "goerli2_config": "${{ env.GOERLI2 }}", "testnet_confi
@Manjeet-Nethermind

2023-09-12 09:55 UTC, wojciechos commented on .github/workflows/build-and-deploy.yml
> +        uses: docker/setup-buildx-action@v2
One hour ago they've released v3, can we update it?

2023-09-12 09:56 UTC, wojciechos commented on .github/workflows/build-and-deploy.yml
> +        uses: docker/login-action@v2
Same here! V3 available

2023-09-12 09:57 UTC, wojciechos commented on .github/workflows/build-and-deploy.yml
> +        uses: actions/checkout@v3
same here - v4 available :D

2023-09-12 09:58 UTC, wojciechos commented on .github/workflows/build-and-deploy.yml
> +        uses: docker/build-push-action@v4
v5 already available :)

2023-09-12 10:01 UTC, wojciechos commented on .github/workflows/build-and-deploy.yml
> +            -d '{"event_type": "${{ env.EVENT_NAME }}", "client_payload":{"name": "${{ env.EVENT_NAME }}", "goerli_config": "${{ env.GOERLI }}", "goerli2_config": "${{ env.GOERLI2 }}", "integration_c
Can we do not deploy goerli2 anymore? It will be deprecated soon, so there is no need to maintain that anymore.

2023-09-12 12:39 UTC, wojciechos approved these changes

2023-09-12 13:13 UTC, Manjeet-Nethermind requested changes
Please Fix the syntax error and use the command substitution $(...)
Define_docker_image_tag

2023-09-13 07:55 UTC, Manjeet-Nethermind approved these changes
LGTM

2023-09-13 07:57 UTC, gehlotanish approved these changes
Looks good to me

2023-09-13 10:24 UTC, AnavarKh approved these changes

2023-09-13 13:24 UTC, merged