Enhancement: Improved L1 Verifier Error Handling
NethermindEth/juno pull request #1388
Opened 2023-10-28 10:23 UTC by aminsato

#1385

2023-10-28 21:18 UTC, joshklop requested changes

2023-10-28 21:18 UTC, joshklop commented on l1/l1.go
> +		return nil
We need to keep trying (i.e., no `return nil`). We'll need to put this in a loop and backoff when we receive an error.

2023-10-30 11:16 UTC, aminsato commented
It still hasn't been reviewed by someone.
@omerfirmak 
@joshklop

2023-10-30 12:26 UTC, joshklop requested changes

2023-10-30 12:26 UTC, joshklop commented on l1/l1.go
> +	for i := 0; i < retryAttempts; i++ {
We should retry forever (never fail).

2023-10-30 12:26 UTC, joshklop commented on l1/l1.go
> +			time.Sleep(backOffDuration)
The backoff should be exponential.

2023-10-31 16:33 UTC, joshklop requested changes

2023-10-31 16:33 UTC, joshklop commented on l1/l1.go
> +			c.log.Warnw("Failed to retrieve Ethereum chain ID: ", err)
```suggestion
			c.log.Warnw("Failed to retrieve Ethereum chain ID, retrying", err)
```
Let's move this below the backoff calculation and add `"waitFor", backoffDuration` to the log so the user knows how long Juno will wait.

2023-10-31 16:33 UTC, joshklop commented on l1/l1.go
> +			time.Sleep(backOffDuration)
These lines should be swapped.

2023-10-31 16:33 UTC, joshklop commented on l1/l1.go
> +		backOffDuration := time.Duration(1) * time.Second
This should go outside the `for` loop, otherwise we reset the backoff every iteration.

2023-10-31 18:16 UTC, joshklop commented
We can wait for https://github.com/NethermindEth/juno/pull/1399 to be merged so we don't have to calculate backoffs and sleep manually.

2024-12-18 11:12 UTC, kirugan commented on l1/l1.go
> +	backOffDuration := time.Duration(1) * time.Second
nit: `backOffDuration := time.Second`

2024-12-20 11:45 UTC, closed without merging