core: Add BlockNumber type
NethermindEth/juno pull request #140
Opened 2022-04-19 23:49 UTC by stdevAdrianPaez

## Changes:

Implement the BlockNumber type to handle the `block_number`field in the feeder models. A `block_number` can be an integer equal to or greater than 0 or the string "pending"

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [x] Yes
- [ ] No

**In case you checked yes, did you write tests??**

- [x] Yes
- [ ] No

2022-04-20 02:32 UTC, stdevMac approved these changes

2022-04-20 02:34 UTC, stdevMac requested changes
Could you please use this type in the places is used the int implementation of BlockNumber?

2022-04-20 02:35 UTC, stdevAdrianPaez commented
> Could you please use this type in the places is used the int implementation of BlockNumber?
> 

Yes, ok

2022-04-20 03:26 UTC, stdevAdrianPaez commented
@stdevMac The `StarkNetBlock` has other issues with JSON decoding, these are the issues when I try to decode a block:

- [ ] `StarknetBlock.Transactions` must be an array of `TxnSpecificInfo`
- [ ] `TxnSpecificInfo.Type` must be of type `string`
- [ ] `StarkNetBlock.TransactionReceipts` must be an array of `TransactionExecution`
- [ ] `Event.Keys` must be of type `[]string`
- [ ] `Event.Data` must be of type `[]strign`
- [ ] `ExecutionResources.NMemoryHoles` must be of type `int64`

2022-04-21 14:28 UTC, stdevMac approved these changes

2022-04-21 16:09 UTC, merged