Test contract address calculation
NethermindEth/juno pull request #164
Opened 2022-05-20 01:11 UTC by joshklop

Resolves #150 

## Changes:
- Add a test for the ArrayDigest function

## Types of changes

What types of changes does your code introduce?

- [X] Code style update (formatting, renaming)
- [X] Refactoring (no functional changes, no api changes)

## Testing
**Requires testing**

- [ ] Yes
- [X] No

## Further comments (optional)

The issue also requests tests for the block hash and transaction hash. These will require significantly more work, since, for example, computing the block hash requires building a [merkle tree](https://github.com/starkware-libs/cairo-lang/blob/2abd303e1808612b724bc1412b2b5babd04bb4e7/src/starkware/starknet/services/api/feeder_gateway/block_hash.py#L60-L64) of all of the transactions. I am currently evaluating how to best tackle that problem.

2022-07-05 22:47 UTC, stdevAdrianPaez approved these changes

2022-07-06 12:18 UTC, tshakalekholoane commented on pkg/crypto/pedersen/pedersen_test.go
>  		},
Delete the tests above now that we have tests that check against IRL data.

2022-07-06 12:19 UTC, tshakalekholoane commented on pkg/crypto/pedersen/pedersen_test.go
> +				"0439218681f9108b470d2379cf589ef47e60dc5888ee49ec70071671d74ca9c6",
Is it possible to reference the URL here instead of CLI command?

2022-07-10 16:59 UTC, stdevMac approved these changes

2022-07-11 09:22 UTC, tshakalekholoane requested changes

2022-07-11 09:22 UTC, tshakalekholoane commented on pkg/crypto/pedersen/pedersen_test.go
> +				Digest(new(big.Int), new(big.Int)).Text(16),
Let's hardcode this as well for consistency.

2022-07-12 00:27 UTC, stdevMac approved these changes

2022-07-12 08:46 UTC, tshakalekholoane approved these changes

2022-07-12 08:46 UTC, merged