Start using gitlab hosted runners for ARM
NethermindEth/juno pull request #2012
Opened 2024-08-01 18:45 UTC by derrix060

Those runners have proper auto-scaling and are able to out-perform the self-hosted one that we had.

2024-08-01 20:57 UTC, kirugan approved these changes

2024-08-02 08:13 UTC, kirugan approved these changes

2024-08-02 08:14 UTC, wojciechos approved these changes

2024-08-02 08:17 UTC, wojciechos requested changes
We should also update the build [docker workflow](https://github.com/NethermindEth/juno/blob/main/.github/workflows/docker-image-build-push.yml#L47). I'm also wondering how long it would take to build the image with this machine. We used an ARM machine to build the ARM image because building it on an AMD machine takes ages

2024-08-02 08:36 UTC, derrix060 commented
well spoted, let me update

2024-08-02 08:40 UTC, derrix060 commented
I've changed to use the 4core machine for the build, it should improve the compilation time

2024-08-02 11:46 UTC, wojciechos approved these changes

2024-08-02 12:07 UTC, merged