Emit events on remote db
NethermindEth/juno pull request #2088
Opened 2024-08-25 07:17 UTC by PriyankMkwna

So first I have added an listener field in DB struct then added code to emit event when a new transaction is created , view operation , update operation and when db is closed . I have also updated the WithListener function .

Fixed #1414

2024-08-26 13:27 UTC, PriyankMkwna commented
I have made some changes that you have suggested.

2024-08-28 10:15 UTC, kirugan commented on db/remote/db.go
> +	listener   db.EventListener
there are some improvements that we can do:
1. set `listener` to `SelectiveListener` in `New` function by default
2. remove nil checks for `d.listener`

2024-08-28 10:16 UTC, kirugan commented on db/remote/db.go
> +		d.listener.OnCommit(time.Since(start))
after removing `d.listener` check consider using `defer func() { d.listener.OnCommit(...)} ` as in the rest of codebase (but only here)

2024-08-28 10:17 UTC, kirugan requested changes
get rid of nil checks + add defer in 1 place

2024-08-28 11:51 UTC, PriyankMkwna commented
Updated dg.go as you have suggested.

2024-08-30 09:53 UTC, kirugan approved these changes

2024-08-30 10:01 UTC, AnkushinDaniil approved these changes

2024-08-30 10:02 UTC, rianhughes approved these changes

2024-08-30 10:08 UTC, kirugan commented
@RuneRogue it's almost done: there is one minor change - see linter issues:
```
db/remote/db.go:31: File is not `gci`-ed with --skip-generated -s standard -s default (gci)
		OnIOCb:     func(write bool, duration time.Duration) {}, 
db/remote/db.go:51: File is not `gci`-ed with --skip-generated -s standard -s default (gci)
	
make: *** [Makefile:89: lint] Error 1
```
you can verify it locally with `make lint`

2024-08-30 13:27 UTC, merged

2024-08-30 13:29 UTC, kirugan commented
@RuneRogue thanks for contribution. Please check OnlyDust