Feat/comms
NethermindEth/juno pull request #245
Opened 2022-06-24 15:24 UTC by D-DePablos

Fixes | Closes | Resolves #185 

## Changes:
- Adding estimate_fee with multiple function inputs

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix
- [x] New Feature

 
## Testing
**Requires testing**

- [x] Yes
- [ ] No

**In case you checked yes, did you write tests??**

- [ ] Yes
- [x] No -> Planning to!
 
**Comments about testing , should you have some** (optional)
In the original implementation I assumed 1 input to the function, which means view functions or those with calldata with more than 1 element don't work. 

I am also using this chance to implement the call_contract functionality.

2022-06-28 15:36 UTC, D-DePablos commented
I have updated the linked issue

2022-07-06 17:20 UTC, stdevMac requested changes

2022-07-07 15:24 UTC, stdevMac approved these changes

2022-07-07 15:47 UTC, smishy05 approved these changes
Looks good to me! Thanks for correcting the comments. That helps a lot!

2022-07-09 14:27 UTC, adriantpaez requested changes

2022-07-09 14:27 UTC, adriantpaez commented on cmd/juno-cli/cli/estimateFee.go
> +	  juno-cli cx estimate_fee 0x0003a4d1be6ae6cccc7b6cc3cc16bbfd092c2a724ffe6be86c7b5b5fe6ec11d0 increase_decrease --network goerli -p -i 1 -i 2
I think `cx` shouldn't be here.`juno-cli cx estimate_fee ...` doesn't work for me, `juno-cli estimate_fee ...` yes

2022-07-14 08:45 UTC, stdevMac approved these changes

2022-07-20 08:22 UTC, merged