Init logger from conf
NethermindEth/juno pull request #264
Opened 2022-07-04 11:10 UTC by v4lproik

Fixes | Closes | Resolves #

## Changes:
- Injecting a new logger instance created from config file properties

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation Update
- [X] Code style update (formatting, renaming)
- [X] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [ ] Yes
- [X] No

**In case you checked yes, did you write tests??**

- [ ] Yes
- [ ] No

## Further comments (optional)

Hi everyone! I have become pretty fond of the this project as I am a fan of Golang and very recently StarkNet - I even started learning some Cairo. Also I have applied to a position at Nethermind and as a bit of a 'refresher' before getting on with the technical interview I would like to run that node in k8s in EKS. Being able to collect the logs in JSON as well as setting the verbosity might obviously come in handy in that case for monitoring purposes. I hope I am not stepping on anyone toes here. If I do, please discard this PR. Happy to keep contributing if you guys are alright with it.

What I have done is basically extending the config so to get information related to the logger - verbosity and json ouput. Once initiating the logger, I replaced the default logger that you use across the app and injected it at the lib level for consistency. Also, I renamed it from Default to Logger for clarity purposes. Let me know if you want to see any other properties being extended through the config file.

2022-07-04 20:21 UTC, stdevAdrianPaez approved these changes

2022-07-07 15:39 UTC, stdevMac requested changes

2022-07-07 15:39 UTC, stdevMac commented on docs/docs/running/config.mdx
> +  verbosity_level: "debug"
On the documentation

2022-07-07 16:07 UTC, v4lproik commented on docs/docs/running/config.mdx
> +  verbosity_level: "debug"
My bad I actually didn't see the description down below. I have just added it :) Let me know if it needs to be added somewhere else.

2022-07-07 17:49 UTC, stdevMac approved these changes

2022-07-07 19:33 UTC, joshklop approved these changes

2022-07-10 22:30 UTC, merged