Speed up fail rest tests
NethermindEth/juno pull request #267
Opened 2022-07-04 15:55 UTC by v4lproik

Resolves #256 

## Changes:
- Extracted the hardcoded retry mechanism implemented in the http Do function.
- Allows the http client to take a retry mechanism as parameter which will then be used in the Do function.
- Test time before this PR
```
ok  	github.com/NethermindEth/juno/pkg/rest/tests	123.929s
```
- Test time after this PR
```
ok  	github.com/NethermindEth/juno/pkg/rest/tests	12.016s
```

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [X] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [ ] Yes
- [X] No

**In case you checked yes, did you write tests??**

- [ ] Yes
- [ ] No

2022-07-04 16:08 UTC, stdevMac approved these changes

2022-07-04 16:21 UTC, stdevMac commented
Just some coverage issues, you can take a look deeply if you look at [here](https://gojuno.xyz/docs/testing/coverage). Very well done work! Thanks for your contributions!

2022-07-04 16:52 UTC, v4lproik commented
I added a test that fails when using the default client implementation and so by extension the default retry mechanism. Coverage should be ok now.

Test time is now at `ok  	github.com/NethermindEth/juno/pkg/rest/tests	18.872s`

2022-07-05 13:31 UTC, tshakalekholoane requested changes
See comments. Otherwise great work! We appreciate your contribution.

2022-07-05 13:31 UTC, tshakalekholoane commented on pkg/rest/tests/rest_test.go
> +	assert.DeepEqual(t, rr.Body.String(), fmt.Sprintf("Invalid request body error:%s", errorMessage))
There's no string formating going on here so let's do a simple string concat.

2022-07-05 14:45 UTC, tshakalekholoane requested changes

2022-07-05 14:45 UTC, tshakalekholoane commented on pkg/rest/tests/rest_test.go
> +	baseApi            = "/feeder_gateway/"
Use consistent case for acronyms i.e. `baseURL` instead of `baseUrl`. See [guide](https://github.com/golang/go/wiki/CodeReviewComments#initialisms).

2022-07-05 14:45 UTC, tshakalekholoane commented on pkg/rest/tests/rest_test.go
> +	httpClient.DoReturns(nil, fmt.Errorf("%s", errorMessage))
Again, no formatting done so we could probably use `errors.New` here.

2022-07-05 14:45 UTC, tshakalekholoane commented on pkg/rest/tests/rest_test.go
> +	queryStr := "http://localhost:8100/feeder_gateway/get_block"
Use string concat with newly created variables.

2022-07-05 14:45 UTC, tshakalekholoane commented on pkg/rest/tests/rest_test.go
> +	assert.DeepEqual(t, rr.Body.String(), "Invalid request body error:"+errorMessage)
Insert space after colon.

2022-07-05 15:34 UTC, v4lproik commented
Thanks for the review @tshakalekholoane. I also ended up extracting query url and fixing the error formatting in the handlers.

2022-07-05 16:27 UTC, tshakalekholoane approved these changes

2022-07-05 17:34 UTC, joshklop approved these changes

2022-07-05 19:31 UTC, merged