removed big int inefficiency
NethermindEth/juno pull request #275
Opened 2022-07-07 11:07 UTC by D-DePablos

Fixes | Closes | Resolves #261 

Removed Big Int intermediate conversion to optimise performance

2022-07-07 11:38 UTC, tshakalekholoane requested changes

2022-07-07 11:38 UTC, tshakalekholoane commented on pkg/crypto/keccak/keccak.go
> +	digest[0] = digest[0] & 3 // Remove the first 6 bits from the first byte.
Top marks! Let's go with the more succinct `digest[0] &= 3` here.

2022-07-08 10:17 UTC, IronGauntlets commented on pkg/crypto/keccak/keccak.go
> +	digest[0] &= 3 // Remove the first 6 bits from the first byte.
```suggestion
        // Remove the first 6 bits from the first byte.
	digest[0] &= 3
```

2022-07-08 15:35 UTC, joshklop approved these changes

2022-07-10 22:32 UTC, stdevMac approved these changes

2022-07-10 22:36 UTC, merged