[WIP] refactor config
NethermindEth/juno pull request #295
Opened 2022-07-22 01:20 UTC by joshklop

## Changes
- Process configurations from various sources (in order of precedence): CLI parameters, environment variables, config file entries, and default values.
- Use perfectly consistent naming conventions regardless of the configuration source
- Never modify the user's environment except for creating database files in locations explicitly provided by the user or in clearly defined default locations.
- Make it as easy as possible for developers to add new configuration options.

Summary:

`cobra` and `viper` are replaced with the amazing [`cli`](https://github.com/urfave/cli). Many of the changes here are motivated by similar techniques used in geth, which also uses the `cli` package. Changes are primarily in the `cmd/juno/main.go` and `cmd/juno/config.go` files. See comments at the top of the `config.go` file for more details.

## Types of changes

What types of changes does your code introduce?

- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (previous configurations will break)
- [ ] Documentation Update (TODO)
- [X] Refactoring (no functional changes, no api changes)
- [X] Build related changes (slightly modified Makefile)

## Testing
**Requires testing**

- [X] Yes
- [ ] No

**In case you checked yes, did you write tests??**

- [ ] Yes
- [X] No (TODO)

2022-07-26 12:54 UTC, adriantpaez approved these changes
LGTM

2022-07-26 13:45 UTC, tshakalekholoane requested changes

2022-07-26 13:45 UTC, tshakalekholoane commented on internal/config/config.go
> +	junoDir := "juno"
This doesn't look to ever be mutated afterwards to let's initialise it as a `const` for clarity.

2022-07-28 09:34 UTC, D-DePablos commented
If we expect the user to use the --starknet-enable flag, it is not routed with make all `starknet enable`. 

Since our [docs](https://gojuno.xyz/docs/intro) indicate the user to `make run`, or `make all`, this would not run correctly as the docs stand. 

![image](https://user-images.githubusercontent.com/42889395/181473213-015fadf6-ce43-4780-806f-ea8bf817ea68.png)

2022-07-28 11:11 UTC, tshakalekholoane approved these changes
LGTM.

2022-08-04 12:14 UTC, stdevMac commented
Can we add more details around Environment vars and params on the docs? @joshklop Thanks in advance

2022-08-04 18:17 UTC, stdevMac approved these changes

2022-08-08 14:15 UTC, merged