Local Github ACTions | Fix docs deployment
NethermindEth/juno pull request #298
Opened 2022-07-22 14:31 UTC by D-DePablos

## Changes:
- Added ACT environment variables
- Investigating Docs deployment error

## Types of changes

What types of changes does your code introduce?
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes

Testing: Local runs are done with this .actrc from an M1 macbook:

-P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest
-P ubuntu-18.04=ghcr.io/catthehacker/ubuntu:act-18.04
-b
--container-architecture linux/amd64

2022-07-22 16:37 UTC, D-DePablos commented
TODO: I think this branch is bugged from changes to one or multiple actions.

2022-07-28 09:47 UTC, D-DePablos commented
This is giving me some problems due to how ACT creates an ACT.env parameter that is not available on GitHub. Actions seem to update when updating the PR, so they were not working for a while. They should be changed with care.

2022-07-31 23:33 UTC, stdevMac approved these changes

2022-08-01 19:22 UTC, joshklop requested changes
Are there more changes with the GitHub actions? I only am seeing changes to the Makefile, go.mod, and go.sum.

2022-08-01 19:22 UTC, joshklop commented on Makefile
> +	go mod tidy
I think implicitly running `go mod tidy` on the `format` command is unnecessary, and obfuscates what the actual command is doing. I personally prefer having `tidy` and `format` separated.

2022-08-08 08:31 UTC, D-DePablos commented
This is quite a bit of a larger headache than I had thought. Additionally, if there is a correct docs staging environment, and smoke tests for Juno, it is not as useful.

The main pain points are related to how in ACT you must use a Docker container, while in GH actions you have a full system. ACT proves to be slower, less reliable, and to force some if conditionals on the workflow files.

2022-08-08 08:31 UTC, closed without merging