[feeder] fix on nil pointer after connection broken
NethermindEth/juno pull request #379
Opened 2022-08-29 22:01 UTC by stdevMac

Resolves #376 

## Description

After a connection was lost, a nil pointer error was thrown. With these changes, the nil pointer cause was deleted, and also changed the waiting iterator.

## Changes:

- Fix nil pointer error on logs after an error fetching from the feeder gateway
- Remove 10 times and check for requests to the feeder gateway, will be forever.

## Types of changes

_Leave only items that describe your changes, remove the rest. Remove this line too._

- Bugfix (non-breaking change which fixes an issue)

## Testing

**Requires testing**: No

**Did you write tests??**: No

## Documentation

**If this requires a documentation update, did you add one?** No

2022-08-30 01:42 UTC, adriantpaez requested changes

2022-08-30 01:42 UTC, adriantpaez commented on pkg/feeder/feeder.go
> +		for i := 0; ; i++ {
Looks like `i` isn't more necessary

2022-08-30 14:51 UTC, joshklop approved these changes
LGTM. I second @adriantpaez suggested change above.

2022-08-30 21:02 UTC, IronGauntlets approved these changes

2022-08-30 22:27 UTC, adriantpaez approved these changes

2022-08-31 09:46 UTC, tshakalekholoane approved these changes

2022-08-31 12:27 UTC, merged