Log local time using RFC822 format
NethermindEth/juno pull request #387
Opened 2022-08-31 19:44 UTC by IronGauntlets

## Description

The logger uses the local time using the RFC822 time format. Now the logs look like the following:

```
       _                    
      | |                   
      | |_   _ _ __   ___   
  _   | | | | | '_ \ / _ \  
 | |__| | |_| | | | | (_) |  
  \____/ \__,_|_| |_|\___/  

Juno is a Go implementation of a StarkNet full node client made with ❤️ by Nethermind.

31 Aug 22 20:41 BST     INFO    juno/juno.go:87 Running Juno with config: {Verbosity:info RpcPort:6060 Metrics:false DatabasePath:config/localdb/goerli Network:goerli EthNode:}
31 Aug 22 20:41 BST     INFO    Sync Service    sync/sync.go:76 Defaulting to syncing from gateway
31 Aug 22 20:41 BST     INFO    rpc/http.go:35  Listening for JSON-RPC connections...
31 Aug 22 20:41 BST     INFO    VM      cairovm/vm.go:139       gRPC server listening at 127.0.0.1:49496
31 Aug 22 20:41 BST     INFO    apiCollector    sync/apiCollection.go:50        Collector Started
31 Aug 22 20:41 BST     INFO    apiCollector    sync/apiCollection.go:75        StateDiff collected     {"BlockNumber": 1713}
31 Aug 22 20:41 BST     INFO    Sync Service    sync/sync.go:156        Synchronized block      {"Number": 1713, "Pending": 315698, "Time": 0.8221195}
```

## Types of changes

- Other (please describe): UI change

## Testing

**Requires testing**: No

2022-08-31 21:34 UTC, stdevMac approved these changes

2022-09-01 09:45 UTC, joshklop requested changes

2022-09-01 09:45 UTC, joshklop commented on internal/log/log.go
>  	// Timestamp format (ISO8601) and time zone (UTC)
```suggestion
	// Timestamp format (ANSIC) and time zone (local)
```

2022-09-01 11:05 UTC, tshakalekholoane commented
The change to local time is welcome but why switch from ISO8601 (`time.RFC3339`)?

2022-09-01 12:19 UTC, tshakalekholoane reviewed
The change to local time is welcome but why switch from ISO8601 (`time.RFC3339`)?

2022-09-01 13:25 UTC, IronGauntlets commented
> The change to local time is welcome but why switch from ISO8601 (time.RFC3339)?

I found it difficult to read. Also with the time zone always set to UTC the suffix `Z` was redundant.

2022-09-01 13:58 UTC, tshakalekholoane approved these changes

2022-09-01 14:13 UTC, joshklop approved these changes

2022-09-01 14:17 UTC, merged