Support Invoke Transaction version 1
NethermindEth/juno pull request #402
Opened 2022-09-07 22:52 UTC by adriantpaez

> ⚠️ Transaction definitions on the protobuf files changes on this PR, and then a previous database populated before this PR will be incompatible

## Description

StarkNet adds the new [Transaction Invoke version 1](https://docs.starknet.io/docs/Blocks/transactions#invoke-transaction-version-1), and we need to add the support to storage on our database.

## Changes:

- The new [`InvokeVersioned`](https://github.com/NethermindEth/juno/blob/adrian/invoke_txn_v1/internal/db/transaction/transaction.proto#L21) message is defined in the [`transaction.proto`](https://github.com/NethermindEth/juno/blob/adrian/invoke_txn_v1/internal/db/transaction/transaction.proto) file and represents an Invoke Transaction of any of the supported versions: [v0](https://docs.starknet.io/docs/Blocks/transactions#invoke-transaction-version-0) and [v1](https://docs.starknet.io/docs/Blocks/transactions#invoke-transaction-version-1)
- The new type [`TransactionInvokeV1`](https://github.com/NethermindEth/juno/blob/de7fe3d6fa6942136c03e24226856a9bf3aa5b8e/pkg/types/transaction.go#L36) is added to the `pkg/types` package and the old transaction type is renamed from `TransactionInvoke` to `TransactionInvokeV0`. The marshal.unmarshal process behind the [`GetTransaction`](https://github.com/NethermindEth/juno/blob/de7fe3d6fa6942136c03e24226856a9bf3aa5b8e/internal/db/transaction/manager.go#L41) and [`PutTransaction`](https://github.com/NethermindEth/juno/blob/de7fe3d6fa6942136c03e24226856a9bf3aa5b8e/internal/db/transaction/manager.go#L28) methods has been updated to support these new types.

## Pending Changes

- Update the sync process to handle this new type of transaction, currently all transactions are taken as v0
- Update RPC, this is part of the upgrade to v0.2.0

## Types of changes

_Leave only items that describe your changes, remove the rest. Remove this line too._

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Testing

**Requires testing**: Yes

**Did you write tests??**: Yes

## Documentation

**If this requires a documentation update, did you add one?** Yes/No

2022-09-09 13:27 UTC, stdevMac approved these changes

2022-09-14 10:56 UTC, tshakalekholoane requested changes

2022-09-14 10:56 UTC, tshakalekholoane commented on internal/rpc/starknet/types.go
> +	BroadcastedTxnCommonProperties
Embedded fields should come first.

```suggestion
	BroadcastedTxnCommonProperties
	TxnHash string `json:"transaction_hash"`
```

2022-09-14 10:56 UTC, tshakalekholoane commented on internal/rpc/starknet/types.go
> +	}
We can avoid zeroing out the arrays.

2022-09-14 10:56 UTC, tshakalekholoane commented on internal/rpc/starknet/types.go
> +	DeployTxnProperties
Embedded fields should appear first.

2022-09-14 10:56 UTC, tshakalekholoane commented on internal/sync/sync.go
> +	txnV1Id                  = new(felt.Felt).SetHex("0x1")
Assignment using the helpers `SetOne` and `SetZero` respectively are less costly.

2022-09-14 11:48 UTC, tshakalekholoane approved these changes

2022-09-14 15:12 UTC, joshklop approved these changes

2022-09-14 18:01 UTC, merged