Iron gauntlets/blocks and transactions
NethermindEth/juno pull request #423
Opened 2022-11-08 12:58 UTC by IronGauntlets

## Description

Add Block and Transaction types as defined in [StrakNet's Technical Documentation](https://docs.starknet.io/documentation/).

## Changes:

- Add Block Struct
- Add Deploy Transaction struct
- Add Invoke Transaction struct
- Add Declare Transaction struct

## Types of changes

- New feature (non-breaking change which adds functionality)
## Testing

**Requires testing**: Yes

**Did you write tests??**: No

2022-11-08 13:02 UTC, omerfirmak commented
@IronGauntlets

2022-11-08 13:39 UTC, jelilat commented
@IronGauntlets According to the docs [here](https://docs.starknet.io/documentation/develop/Blocks/transactions/), `deploy transaction` and `invoke transaction 0` is depreciated. We should be using `invoke transaction 1` instead.

2022-11-08 13:44 UTC, jelilat commented on core/Transaction.go
> +	EntryPointSelector *felt.Felt
Use `invoke transaction 1` instead as explained [here](https://docs.starknet.io/documentation/develop/Blocks/transactions/). It does not include `EntryPointSelector`

2022-11-08 13:44 UTC, jelilat commented on core/Transaction.go
> +type DeployTransaction struct {
`deploy` is depreciated. We should use `deploy syscall` that's explained [here](https://docs.starknet.io/documentation/develop/Contracts/contract-classes/) instead.

2022-11-08 13:56 UTC, joshklop requested changes

2022-11-08 13:56 UTC, joshklop commented on core/Transaction.go
> +	version *felt.Felt
Maybe the version should be a `uint`?
```suggestion
	version uint
```

2022-11-08 14:30 UTC, joshklop commented on core/Transaction.go
> +	version *felt.Felt
Thanks to @omerfirmak for pointing out that version is a felt in the specs.

2022-11-09 14:59 UTC, joshklop requested changes
Tiny tiny detail: should the `Transaction.go` file be capitalized? `block.go` is not.

2022-11-09 14:59 UTC, joshklop commented on core/Transaction.go
> +	nonce *felt.Felt
Should the nonce be a public field?
```suggestion
	Nonce *felt.Felt
```

2022-11-09 15:05 UTC, IronGauntlets commented
> should the Transaction.go file be capitalized?

No, it should not. I have updated the file name.

2022-11-09 15:11 UTC, joshklop approved these changes

2022-11-09 15:24 UTC, merged