add gateway test
NethermindEth/juno pull request #489
Opened 2023-01-07 13:39 UTC by liusanchuan

Fixes  #488 
## Description

Add test to cover `gateway.go`

## Changes:

- Add test in `juno/clients/gateway_test.go`

## Types of changes

- Other (please describe):  Add more test

## Testing

**Requires testing**: Yes

**Did you write tests??**: Yes

## Documentation

**If this requires a documentation update, did you add one?** No

2023-01-08 09:16 UTC, liusanchuan commented
@joshklop 
please make a review
ok      github.com/NethermindEth/juno/clients   0.085s  coverage: 100.0% of statements

2023-01-09 12:59 UTC, joshklop requested changes
Thanks! To start, can you please break up the single monolithic test into multiple test cases? See Learn Go with Tests (liked in corresponding issue) for examples.

2023-01-09 15:42 UTC, liusanchuan commented on clients/gateway_test.go
> +	})
@joshklop  Do you think should this format split into multiple test function?

2023-01-09 15:43 UTC, liusanchuan commented
@joshklop ,  Thanks for your point out. Please review my fix code.

2023-01-10 12:00 UTC, IronGauntlets approved these changes
LGTM!

Please fix the conflicts and clean the git history and follow the commit message guidelines mentioned [here](https://cbea.ms/git-commit/). Or you can squash and merge but please make sure to update the git commit message according to the guide mentioned above.

2023-01-10 13:28 UTC, joshklop approved these changes
Fantastic stuff. Thanks @liusanchuan!

2023-01-10 16:08 UTC, liusanchuan commented
Hi @IronGauntlets , I have squeezed my branch comments :) , could you have a review?

2023-01-10 17:09 UTC, merged

2023-01-10 17:27 UTC, liusanchuan commented
@joshklop @IronGauntlets Thanks for your guide, I learned a lot from this cooperation. If there is others tasks, welcome to assign to me. :)