Iron gauntlets/trie
NethermindEth/juno pull request #491
Opened 2023-01-09 13:21 UTC by IronGauntlets

Fixes | Closes | Resolves #

## Description

_Explanation about why the PR is necessary._

## Changes:

- Change 1
- Change 2

## Types of changes

_Leave only items that describe your changes, remove the rest. Remove this line too._

- Bugfix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Update
- Code style update (formatting, renaming)
- Refactoring (no functional changes, no api changes)
- Build related changes
- Other (please describe): 

## Testing

**Requires testing**: Yes/No

**Did you write tests??**: Yes/No

## Documentation

**If this requires a documentation update, did you add one?** Yes/No

2023-01-09 13:42 UTC, omerfirmak requested changes

2023-01-09 13:42 UTC, omerfirmak commented on core/trie/trie.go
> +		return nil, nil
Empty trie has a commitment of `0`, so this should be reverted.

2023-01-10 11:49 UTC, jelilat requested changes

2023-01-11 11:54 UTC, jelilat approved these changes

2023-01-11 12:24 UTC, merged