Node setup and configuration refactors
NethermindEth/juno pull request #634
Opened 2023-03-15 18:49 UTC by joshklop

See commits.

2023-03-15 21:10 UTC, wojciechos approved these changes

2023-03-16 12:47 UTC, jelilat requested changes
Should run `go mod tidy`

2023-03-17 09:46 UTC, omerfirmak approved these changes
Should be good to merge after addressing linter warnings.

2023-03-17 12:06 UTC, jelilat approved these changes
Nice work!

Should be good to go once the linting errors are fixed

2023-03-20 09:10 UTC, merged